# Generated by Django 5.0.6 on 2024-07-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalstats', '0002_solarenergyrecord_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarenergyrecord',
            old_name='country',
            new_name='county',
        ),
    ]
