# Generated by Django 5.0.6 on 2024-07-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalstats', '0006_alter_solarenergyrecord_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarenergyrecord',
            name='power_generated',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
